### ISSUE TITLE
tekton-approval-task on arm64

### ISSUE THREAD

**Issue by brainbug95** [automatiko-io/automatiko-approval-task#17]
Hi,

I want to evaluate this approval-task with tekton on kubernetes k3s destribution arm64. Unfortunatly there seems to be no build of the underlying docker image for arm64. I found only amd64.

Can you please provide an arm64 build as well or alternatively instructions on how to compile it myself?

Much appreciated. BR,
Christian

**Comment by mswiderski** [comment]
I thought it will be as simple as using different GitHub runner but looks like there is no listed runners for arm64. Will try to build something locally based on apple silicon and see if that will make any difference. Will keep you posted.

**Comment by mswiderski** [comment]
having hard time to build it as native image due to lack of good arm64 environment. But to run it with jvm model it should be as simple as adding this property `quarkus.jib.base-jvm-image=arm64v8/eclipse-temurin:21-ubi9-minimal` to `application.properties` and build container image with `mvn clean package -Pcontainer`

**Comment by brainbug95** [comment]
I successfully build an arm64 container image locally and it is running now.

`2024-06-20 08:31:18,039 INFO  [io.quarkus] (main) automatiko-approval-task 0.10.1 on JVM (powered by Quarkus 3.2.2.Final) started in 7.490s. Listening on: http://0.0.0.0:8080`

Thank you very much for your support.

BR,
Christian

**Comment by mswiderski** [comment]
great to hear!
